In [2]:
import pandas as pd

In [2]:
a=pd.read_parquet("C:/Users/nikhi/Downloads/yellow_tripdata_2022-03.parquet")
a=a.copy()

In [3]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3627882 entries, 0 to 3627881
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int64
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int64
 8   DOLocationID           int64
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  airport_fee            float64
dtypes: datetime64[us](2), float64(12), int64(4), object(1)
memory usage: 525.9+ MB

In [4]:
a.head(10)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,1,2022-03-01 00:13:08,2022-03-01 00:24:35,1.0,2.40,1.0,N,90,209,2,10.0,3.00,0.5,0.00,0.0,0.3,13.80,2.5,0.00
1,1,2022-03-01 00:47:52,2022-03-01 01:00:08,1.0,2.20,1.0,N,148,234,2,10.5,3.00,0.5,0.00,0.0,0.3,14.30,2.5,0.00
2,2,2022-03-01 00:02:46,2022-03-01 00:46:43,1.0,19.78,2.0,N,132,249,1,52.0,0.00,0.5,11.06,0.0,0.3,67.61,2.5,1.25
3,2,2022-03-01 00:52:43,2022-03-01 01:03:40,2.0,2.94,1.0,N,211,66,1,11.0,0.50,0.5,4.44,0.0,0.3,19.24,2.5,0.00
4,2,2022-03-01 00:15:35,2022-03-01 00:34:13,1.0,8.57,1.0,N,138,197,1,25.0,0.50,0.5,5.51,0.0,0.3,33.06,0.0,1.25
5,1,2022-03-01 00:11:57,2022-03-01 00:53:05,2.0,14.00,1.0,N,132,33,1,43.5,1.75,0.5,9.20,0.0,0.3,55.25,0.0,1.25
6,2,2022-03-01 00:05:11,2022-03-01 00:08:22,1.0,0.61,1.0,N,166,151,1,4.5,0.50,0.5,1.00,0.0,0.3,6.80,0.0,0.00
7,2,2022-03-01 00:30:56,2022-03-01 00:46:21,1.0,2.83,1.0,N,74,238,1,13.0,0.50,0.5,3.70,0.0,0.3,18.00,0.0,0.00
8,2,2022-03-01 00:30:28,2022-03-01 00:30:36,1.0,0.10,1.0,N,145,145,3,-2.5,-0.50,-0.5,0.00,0.0,-0.3,-3.80,0.0,0.00
9,2,2022-03-01 00:30:28,2022-03-01 00:30:36,1.0,0.10,1.0,N,145,145,2,2.5,0.50,0.5,0.00,0.0,0.3,3.80,0.0,0.00

In [5]:
a["passenger_count"].value_counts()

passenger_count
1.0    2626588
2.0     509493
3.0     130829
0.0      74319
5.0      69333
4.0      53109
6.0      46365
7.0         22
8.0          9
9.0          1
Name: count, dtype: int64

In [6]:
a["PULocationID"].value_counts()

PULocationID
237    168294
132    152733
161    152354
236    152289
162    122274
        ...
184         1
2           1
251         1
214         1
245         1
Name: count, Length: 257, dtype: int64

In [7]:
a["PULocationID"].sort_values(ascending=True)

2306985      1
1059114      1
1518864      1
1275650      1
2825373      1
          ...
3536577    265
3536579    265
2156211    265
3536582    265
2156027    265
Name: PULocationID, Length: 3627882, dtype: int64

In [8]:
s=a[a["fare_amount"]>0]
c=s["fare_amount"].max()

c

np.float64(1777.0)

In [9]:
c=a[a["trip_distance"]>2000]
c["trip_distance"].value_counts(ascending=True)

trip_distance
53440.55     1
7170.55      1
59918.99     1
33249.83     1
85671.20     1
            ..
54041.77     1
125804.71    1
181534.72    1
81060.74     1
78809.21     1
Name: count, Length: 91, dtype: int64

In [10]:
a["passenger_count"].value_counts()

passenger_count
1.0    2626588
2.0     509493
3.0     130829
0.0      74319
5.0      69333
4.0      53109
6.0      46365
7.0         22
8.0          9
9.0          1
Name: count, dtype: int64

In [12]:
a.columns

Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag',
       'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount', 'congestion_surcharge', 'airport_fee'],
      dtype='object')

In [3]:
d=pd.read_parquet("C:/Users/nikhi/Downloads/Large-Scale-Taxi-Demand-Forecasting-System/features_store/selected_features.parquet")

In [4]:
d.head(5)

,hour_timestamp,demand,avg_fare,avg_distance,zone_id,hour_of_day,day_of_week,month,is_weekend,is_rush_am,...,roll_mean_24h,roll_mean_48h,roll_mean_168h,roll_std_6h,roll_std_24h,zone_mean_demand,zone_std_demand,zone_max_demand,borough,borough_encoded
0,2022-03-09 17:30:00,1.0,8.000000,1.87,4,17,2,3,0,0,...,3.083333,2.583333,4.434524,1.471960,1.471960,4.973366,6.345763,41.0,Bronx,0
1,2022-03-09 18:30:00,1.0,13.500000,3.47,4,18,2,3,0,0,...,3.000000,2.520833,4.428571,1.632993,1.532262,4.973366,6.345763,41.0,Bronx,0
2,2022-03-09 20:30:00,1.0,21.500000,6.76,4,20,2,3,0,0,...,3.000000,2.479167,4.428571,1.264911,1.532262,4.973366,6.345763,41.0,Bronx,0
3,2022-03-10 01:30:00,1.0,11.000000,3.03,4,1,3,3,0,0,...,3.000000,2.458333,4.410714,1.211060,1.532262,4.973366,6.345763,41.0,Bronx,0
4,2022-03-10 02:30:00,3.0,10.166667,1.92,4,2,3,3,0,0,...,2.875000,2.458333,4.404762,1.211060,1.569062,4.973366,6.345763,41.0,Bronx,0

In [2]:
dict1={"a":3,"b":2,"c":30}
dict2={"a":3,"b":2,"c":70}
b=max(dict1.items(),key=lambda x:x[1])
b=b[0]
b2=max(dict2.items(),key=lambda x:x[1])
b2=b2[0]
from collections import Counter
c=Counter(b)
c=c.most_common(n=1)
c[0][0]

'c'

In [3]:
dict1["a"]

3